# This is a basic workflow to help you get started with Actions

name: workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'Golang/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get latest sha of 8 digits.
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse HEAD | cut -c 33-40)" >> $GITHUB_ENV
          echo $GITHUB_ENV
          
      - name: Build
        run: |
          cd Golang
          for file in */; do
          echo $file
          if [ $file -eq ]
          #docker build $file/.
          # docker build -t ghcr.io/deviprasadnaik/workflow-test/golang:alpine-${{ env.GITHUB_SHA_SHORT }} $file/.
          # docker build -t ghcr.io/deviprasadnaik/workflow-test/golang:alpine-latest $file/.
          # docker images -a
          done
      # Runs a single command using the runners shell
      # - name: Log into container registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Login to GitHub Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ghcr.io
      #     username: deviprasadnaik
      #     password: ${{ secrets.DOCKER_SECRET }}

      # - name: Push image to Github Container Registry
      #   run: |
      #     #docker images -a
      #     docker image push --all-tags ghcr.io/deviprasadnaik/workflow-test/golang
